[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/bc/C/rpc"

[etherscan]
coston2 = { key = "${FLARE_API_KEY}", url = "https://coston2-explorer.flare.network/api", chain = 114 } 