services:
  postgres:
    image: postgres:13
    container_name: delasoja-postgres
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: delasoja
      POSTGRES_PASSWORD: delasoja
      POSTGRES_DB: delasoja
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delasoja-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U delasoja -d delasoja'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s


networks:
  delasoja-network:
    driver: bridge

volumes:
  postgres_data: